services:
  db:
    image: postgres
    volumes:
      - ~/data/rails-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      DATABASE_URL: db://postgres:password@db:5432/rails_pg_tailwind_docker_development
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rails:
    build: .
    tty: true
    stdin_open: true
    command: sh -c "rm -f tmp/pids/server.pid && bin/rails server -p 3000 -b 0.0.0.0"
    volumes:
      - .:/rails-pg-tailwind-docker
    environment:
      RAILS_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGHOST: db
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
